### ISSUE TITLE
Package and paper To Do (Dec 22)

### ISSUE THREAD

**Issue by dicook** [numbats/woylier#10]
- [x] Create a rotationally more variant splines2d function, that calculates only y~x (Zola)
- [x] Use PCs of rates, to remove linear association (Zola)
- [x] Generate a random starting basis, so both methods can run from this. (Zola)
- [x] ~~Create a new index that has very different values depending on rotation (Di)~~
- [x] ~~Simulate an example with strong rotational variance (Di)~~
- [x] CRAN checks on package (DC)
- [x] pkgdown web site

**Comment by zolabat** [comment]
Check error:
1 error ✖ | 2 warnings ✖ | 5 notes ✖
Error: R CMD check found ERRORs
Execution halted

Exited with status 1.

❯ checking examples ... ERROR
  Running examples in ‘woylier-Ex.R’ failed
  The error most likely occurred in:
  
  > base::assign(".ptime", proc.time(), pos = "CheckExEnv")
  > ### Name: grand_tour_givens
  > ### Title: Create a grand tour with Givens interpolation
  > ### Aliases: grand_tour_givens
  > 
  > ### ** Examples
  > 
  > data(sine_curve)
  > tourr::animate(sine_curve, grand_tour_givens(), tourr::display_xy())
  Converting input data to the required matrix format.
  Error in basis_init(ncol(data), d) : could not find function "basis_init"
  Calls: <Anonymous> -> new_tour -> tour_path -> generator
  Execution halted

**Comment by dicook** [comment]
- [x] change up fig 1 to use new_splines2d, and show 4 rotations: PC2 v PC1  through to PC1 v PC2 with 30 and 45 degrees in between 
- [x] update pkgdown site, try to get hex sticker image, and articles on usage

**Comment by zolabat** [comment]
Closed the issue as completed
