### ISSUE TITLE
To do Feb 8

### ISSUE THREAD

**Issue by dicook** [numbats/woylier#12]
- [x] Complete address fields
- [ ] Make small multiple plots for pdf, to substitute for gifs
- [x] fix error that appears for the geodesic path on the sine curve
- [x] Explain the new_splines2d index, and why we are using this - early in paper
- [ ] organise the application section
    - [ ] with index computed for PC1 v PC2
    - [ ] decide on selection of plots
    - [ ] fix gifs/pdf version
    - [ ] explain what is found
- [x] spell checks, read, Grammarly and word tune

**Comment by zolabat** [comment]
Succesfully submited to CRAN. Yay!

**Comment by dicook** [comment]
🤞🏻

> On 5 Mar 2023, at 8:21 pm, zolabat ***@***.***> wrote:
> 
> 
> Succesfully submited to CRAN. Yay!
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.
> 

cheers,
Di

---
Dianne Cook
***@***.***
