### ISSUE TITLE
Week 8 To Do's

### ISSUE THREAD

**Issue by dicook** [numbats/woylier#6]
- [x] making givens_full_path run everything, so then make other functions not exported
- [x] generate torus code (DI)
- [x] fix is_orthonormal in tourr (DI)
- [x] calculate tau needs expanding to two angles, when d=2
- [x] construct rotation matrix generates 2
- [x] multiplication multiplies the two matrices and then the data
- [x] tau1 and tau2 are divided into steps, to generate moving planes

**Comment by dicook** [comment]
Oh, `tourr::basis_random()` produces an othonormal basis, so there is no need to wrap this in tourr::orthonormalise(). So all example code can be simplified

**Comment by dicook** [comment]
The code for generating the torus is in `preprojection_example.R`, you can add this into `generate_space_view()` for when d=2.

**Comment by dicook** [comment]
Ahhhh,` orthonormalisation_by() `needed to completely do the orthonormalisation. All is good now when you re-install the tourr package @zolabat

**Comment by zolabat** [comment]
> Oh, `tourr::basis_random()` produces an othonormal basis, so there is no need to wrap this in tourr::orthonormalise(). So all example code can be simplified

done

**Comment by zolabat** [comment]
> Ahhhh,`orthonormalisation_by()`needed to completely do the orthonormalisation. All is good now when you re-install the tourr package @zolabat

Thank you. It works perfectly. Now I'm working on 2D.

**Comment by zolabat** [comment]
> > Ahhhh,`orthonormalisation_by()`needed to completely do the orthonormalisation. All is good now when you re-install the tourr package @zolabat
> 
> Thank you. It works perfectly. Now I'm working on 2D.
Hi Di,

I was wondering if the update in tourr_0.6.1 version? It's the lastest CRAN version but orthonormalise_by() function seems not updated. I could be wrong. @dicook

**Comment by zolabat** [comment]
It turns out there are 5 different angles and rotation matrices involved in the case of 2D. Completed the tasks above in try_2d.R file.

**Comment by dicook** [comment]
You need to use the GitHub version of tourr: https://github.com/ggobi/tourr (sorry, just saw this now)
