### ISSUE TITLE
Week 10 to do

### ISSUE THREAD

**Issue by zolabat** [numbats/woylier#8]
- [x] Write the Introduction
- [x] Add diagrams to the report, and small examples of the math
- [x] Adding a plot in the examples
- [ ] Adding the stepsize function to determine the number of steps
- [x] Simulated data function
- [ ]

**Comment by dicook** [comment]
There is a splines example to help with the motivation section, now. See the code at the bottom of data-raw/sine.R

Also update your tourr package. To be able to use the splits function outside of tourr needed some change to the code.

**Comment by dicook** [comment]
Needs a hex sticker!

**Comment by dicook** [comment]
Sine curve data needs to have the variables standardised - think it's not by default, which makes some things odd.
