### ISSUE TITLE
Angular speed

### ISSUE THREAD

**Issue by uschiLaa** [numbats/woylier#9]
Maybe the angular speed is based on geodesic distance right now? Looks like it keeps changing, sometimes very fast because of in-plane rotation.

**Comment by dicook** [comment]
Oh, you mean it even works, sort of! Yes, the step size is something that I'm not quite sure how to enter.

There will be a lot of within-plane rotation, which is what prevents it from being generally used. The geodesic is more aesthetic.

Maybe we can spend a few minutes on this tonight after Sherry's meeting.

**Comment by uschiLaa** [comment]
This is still using the interpolate function, which is computing the number of steps as

  dists <- sapply(2:n, function(i) {
        proj_dist(basis_set[[i - 1]], basis_set[[i]])
    })
    steps <- sum(ceiling(dists/angle)) * 2

so using the geodesic distance (dists) and the angular step size (angle). Would need an alternative version of calculating the distances that accounts for the in-plane spin.
